Manage_referees/urls.py
from django.contrib import admin
from django.urls import path

from Question_manager import views as quest
from Test_manager import views as test
from User_manager import views as user
from Organization_test import views as orga

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user.MainPage.as_view(), name="main_page"),
    path('signup/', user.SignUp.as_view(), name='sign_up'),
    path('login/', user.Login.as_view(), name='login'),
    path('manage_users/', user.ManageUsers.as_view(), name="manage_users"),
    path('manage_group/', user.ManageGroups.as_view(), name='manage_groups'),
    path('questions/', quest.QuestionTable.as_view(), name="all_questions"),
    path('create_question/', quest.CreateQuestion.as_view(), name='create_question'),
    path('create_test/', test.CreateTest.as_view(), name="create_test"),
    path('edit_test/<slug:slug>', test.EditTest.as_view(), name="edit_test"),
    path('delete_test/<slug:slug>', test.DeleteTest.as_view(), name="delete_test"),
    path('logout/', user.Logout.as_view(), name="logout"),
    path('group/<int:id>', user.GroupDetails.as_view(), name="group_details"),
    path('browse_tests/', test.DisplayAllTest.as_view(), name="browse_tests"),
    path('test_details2/<slug:slug>', test.TestDetails.as_view(), name="test_detail_other"),
    path('add_question_to_test/<slug:testslug>/<slug:questionslug>', test.AddQuestionToTest.as_view(), name="add_question_to_test"),
    path('edit_question/<slug:slug>', quest.EditQuestion.as_view(), name="edit_question"),
    path('delete_question/<slug:slug>', quest.DeleteQuesiton.as_view(), name="delete_question"),
    path('remove_question_from_test/<slug:slug>/<int:id>', test.RemoveQuestionFromTest.as_view(), name="remove_question_from_test"),
    path('no_permission/', user.NoPermission.as_view(), name="no_permission"),
    path('edit_user/<slug:slug>', user.EditUser.as_view(), name="edit_user"),
    path('reset_password/<slug:slug>', user.ResetPassword.as_view(), name="reset_password"),
    path('organize_test/', orga.OrganizeTest.as_view(), name="organize_test"),
    path('test_solving/', orga.TestForUserList.as_view(), name="test_solving"),
    path('specific_test_solve/<slug:slug>', orga.SpecificTestToSolve.as_view(), name="specific_test_solve"),
    path('result_of_test/<slug:slug>', orga.SpecificTestSolved.as_view(), name="result_of_test"),
    path('history_of_tests/', orga.UserHistoryOfTests.as_view(), name="user_history"),
    path('all_tests_to_check/', orga.DisplayAllTests.as_view(), name="all_tests_to_check"),
    path('specific_test_to_check/<slug:testslug>/<slug:userslug>', orga.CheckSpecificUserTest.as_view(), name="specific_test_to_check"),
    path('stats', orga.Statistics.as_view(), name="statistics"),
    path('about', user.About.as_view(), name="about"),
    path('answers_managment', quest.ManageQuestionsAnswers.as_view(), name="answers_managment"),
    path('add_answer', quest.AddAnswer.as_view(), name="add_answer"),
    path('test_details/<slug:slug>', test.TestDetailsOther.as_view(), name="test_detail"),
    path('test_details3/<slug:slug>', test.TestDetailsOtherJson.as_view(), name="test_detail_other_json"),
    path('questions_not_in_test/<slug:slug>', test.QuestionsNotInTest.as_view(), name="question_not_in_test_json"),
]

Organize_test/models.py
from django.db import models
from User_manager.models import League, User
from Test_manager.models import QuestionTest
import datetime
from django.template.defaultfilters import slugify

# Create your models here.
class OrganiseTest(models.Model):
    test_for_league = models.ForeignKey("User_manager.League", on_delete=models.CASCADE)
    test_number = models.ForeignKey("Test_manager.QuestionTest", on_delete=models.CASCADE)
    date_time = models.DateTimeField(verbose_name="Data i godzina testu")
    slug = models.CharField(max_length=200, unique=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(str(self.date_time) + str(self.test_for_league) + " " +
                                str(int(datetime.datetime.now().timestamp())))
        return super().save(*args, **kwargs)


class UserSolving(models.Model):
    user = models.ForeignKey("User_manager.User", on_delete=models.CASCADE)
    test_number = models.ForeignKey("Test_manager.QuestionTest", on_delete=models.CASCADE)
    question = models.ForeignKey("Test_manager.QuestionTest", on_delete=models.CASCADE, related_name="question_from_test")
    user_response = models.CharField(max_length=100)
    result = models.FloatField()

Test_manager/models.py
from django.db import models
from django.template.defaultfilters import slugify
from User_manager.models import User, League
import datetime


# Create your models here.
class AllTest(models.Model):
    test_name = models.CharField(max_length=100)
    date = models.CharField(max_length=100)
    for_league = models.ForeignKey('User_manager.League', on_delete=models.PROTECT)
    created_by = models.ForeignKey('User_manager.User', on_delete=models.PROTECT, null=True, blank=True)
    slug = models.CharField(max_length=200, unique=True, null=True, blank=True)
    questions = models.ManyToManyField("Questions", through="QuestionTest")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.test_name + " " + str(int(datetime.datetime.now().timestamp())))
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.test_name


class QuestionTest(models.Model):
    test = models.ForeignKey("AllTest", on_delete=models.CASCADE, related_name="test")
    question = models.ForeignKey("Questions", on_delete=models.CASCADE, related_name="questions")

    def __str__(self):
        return self.test.test_name


class Questions(models.Model):
    add_question = models.TextField(verbose_name="Treść pytania")
    question_possible_answer = models.ManyToManyField("Question_manager.AllPossibleAnswers", through="PossibleAnswers")
    question_correct_answer = models.ManyToManyField("Question_manager.AllPossibleAnswers", related_name="question_correct_answer", through="CorrectAnswer")
    for_league = models.ForeignKey("User_manager.League", on_delete=models.PROTECT)
    added_by = models.ForeignKey('User_manager.User', on_delete=models.PROTECT)
    added_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now=True)
    slug = models.CharField(max_length=200, unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.add_question[:50] + " " + str(int(datetime.datetime.now().timestamp())))
        return super().save(*args, **kwargs)

class PossibleAnswers(models.Model):
    question = models.ForeignKey("Questions", on_delete=models.CASCADE)
    question_possible_answers = models.ForeignKey("Question_manager.AllPossibleAnswers", on_delete=models.CASCADE)

class CorrectAnswer(models.Model):
    question = models.ForeignKey("Questions", on_delete=models.CASCADE)
    question_correct_answers = models.ForeignKey("Question_manager.AllPossibleAnswers", on_delete=models.CASCADE)

User_manager/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import datetime

from django.template.defaultfilters import slugify


# Create your models here.
class User(AbstractUser):
    phone_number = models.IntegerField(verbose_name="Numer telefonu", null=True)
    league = models.ForeignKey('League', on_delete=models.PROTECT, null=True)
    slug = models.CharField(max_length=200, unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.username + " " + str(int(datetime.datetime.now().timestamp())))
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.first_name + " " + self.last_name


class League(models.Model):
    which_league = models.CharField(max_length=100, verbose_name="Liga/klasa")
    slug = models.CharField(max_length=200, unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.which_league + " " + str(int(datetime.datetime.now().timestamp())))
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.which_league

Organize_test/forms.py
from django import forms
from django.forms import ModelForm, RadioSelect, DateTimeInput

from Organize_test.models import OrganiseTest


class OrganizeTestForm(ModelForm):
    class Meta:
        model = OrganiseTest
        exclude = ['slug']
        widgets = {
            "test_for_league": RadioSelect(choices=[]),
            "test_number": RadioSelect(choices=[]),
            "date_time": DateTimeInput()
        }
        labels = {
            "test_for_league": "Dla klasy",
            "test_number": "Który test",
            "date_time": "Data/godzina"
        }

class SolveTestForm(forms.Form):
    answer = forms.CharField(max_length=50)

templates/__base__.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/d00559e887.js" crossorigin="anonymous"></script>
    <script src="{% static 'app.js' %}"></script>
    {% block script %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body id="body-pd" class="body-pd">
<!--header -->
    <header class="header body-pd" id="header">

        <div class="header_toggle"> <i class='bx bx-menu bx-x' id="header-toggle"></i></div>
        <p style="margin-top:4cm;" id="timer"></p>
        <img src="{% static 'logo2.jpg' %}" alt="Pomorski Związek Piłki Nożnej" id="mainlogo">


    </header>
<!--sidebar -->
    <div class="l-navbar show" id="nav-bar">
        <nav class="nav">
            <div> <a href="{% url 'main_page' %}" class="nav_logo"> <i class='fas fa-home dropdown'></i> <span class="nav_logo-name">Strona główna</span> </a>
                    {% if user.is_authenticated %}
                        <small style="margin-left: 5%; color: white">Zalogowany jako:<BR></small>
                        <small style="margin-left: 5%; color: white">{{ user.first_name }} {{ user.last_name }}</small><BR><BR>
                    {% endif %}
                <div class="nav_list">
                    {% if user.is_authenticated %}
                        <a href="#" class="nav_link active dropdownclass"><i class='fas fa-pencil'></i><span class="nav_name">Testy <i class="fas fa-angle-right dropdownarrow"></i></span> </a>
                            <div class="sub-menu">
                                {% if perms.Test_manager.add_alltest %}
                                    <a href="{% url 'create_test' %}" class="nav_link active"><i class="fa-sharp fa-solid fa-plus"></i>Stwórz</a>
                                    <a href="{% url 'browse_tests' %}" class="nav_link active"><i class="fa-sharp fa-solid fa-magnifying-glass"></i>Przeglądaj</a>
                                    <a href="{% url 'organize_test' %}" class="nav_link active"><i class="fa-solid fa-font"></i>Organizuj test</a>
                                {% endif %}
                               <a href="{% url 'test_solving' %}" class="nav_link active"><i class="fa-solid fa-check"></i>Rozwiąż test</a>
                               <a href="{% url 'user_history' %}" class="nav_link active"><i class="fa-solid fa-landmark"></i>Historia</a>
                             </div>
                    {% endif %}
                    {% if perms.Test_manager.view_questions %}
                        <a href="#" class="nav_link active dropdownclass">
                        <i class="fa-solid fa-question"></i>
                        <span class="nav_name">Pytania <i class="fas fa-angle-right dropdownarrow"></i></span></a>
                        <div class="sub-menu">
                            {% if perms.Test_manager.add_questions %}
                               <a href="{% url 'create_question' %}" class="nav_link active"><i class="fa-sharp fa-solid fa-plus"></i>
                                   <span class="nav_name">Dodaj</span></a>
                            {% endif %}
                           <a href="{% url 'all_questions' %}" class="nav_link active"><i class="fa-sharp fa-solid fa-magnifying-glass"></i>
                               <span clas="nav_name">Przeglądaj</span></a>
                         </div>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <a href="#" class="nav_link active dropdownclass"> <i class='fas fa-users'></i><span class="nav_name">Zarządzaj <i class="fas fa-angle-right dropdownarrow"></i></span> </a>
                    {% endif %}
                    <div class="sub-menu">
                    {% if user.is_authenticated %}
                           <a href="{% url 'edit_user' user.slug %}" class="nav_link"><i class="fa-solid fa-gear"></i><span class="nav_name">Edytuj profil</span> </a>
                    {% endif %}
                    {% if perms.User_manager.change_user %}
                       <a href="{% url 'manage_users' %}" class="nav_link"><i class='bx bx-user nav_icon'></i><span class="nav_name">Sędziowie</span> </a>
                       <a href="{% url 'manage_groups' %}" class="nav_link"><i class='fas fa-users'></i><span class="nav_name">Grupy</span></a>
                        {% endif %}
                    {% if perms.Test_manager.view_alltest %}
                       <a href="{% url 'all_tests_to_check' %}" class="nav_link active"><i class="fa-solid fa-square-poll-vertical"></i>
                           <span class="nav_name">Przeglądaj wyniki</span></a>
                    {% endif %}
                    {% if perms.Test_manager.add_possibleanswers %}
                       <a href="{% url 'answers_managment' %}" class="nav_link active"><i class="fa-solid fa-spell-check"></i>
                           <span class="nav_name">Dostępne odpowiedzi</span></a>
                    {% endif %}
                     </div>
                    <a href="{% url 'statistics' %}" class="nav_link"> <i class='fas fa-chart-line'></i><span class="nav_name">Statystyki</span> </a>
                    <a href="{% url 'about' %}" class="nav_link"><i class="fa-solid fa-info"></i><span class="nav_name">O aplikacji</span> </a>
                </div>
            </div>
        <div>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="nav_link"><i class='bx bx-log-out nav_icon'></i> <span class="nav_name">Wyloguj</span> </a>
            {% else %}
                <a href="{% url 'login' %}" class="nav_link"><i class='fas fa-sign-in-alt'></i> <span class="nav_name">Zaloguj</span> </a>
                <a href="{% url 'sign_up' %}" class="nav_link"><i class='fas fa-user-plus'></i> <span class="nav_name">Rejestracja</span> </a>
            {% endif %}
        </div>
        </nav>
    </div>

    <div class="height-100 bg-light" id="contentpage">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
        {% block content %}
        {% endblock %}
    </div>
    <!--Container Main end-->
   <script type="text/javascript">
   $(document).ready(function(){
     //jquery for toggle sub menus
     $('.dropdownclass').click(function(){
       $(this).next('.sub-menu').slideToggle();
       $(this).find('.dropdownarrow').toggleClass('rotate');
     });
   });
   </script>
    <script>
    let tdelement = document.querySelectorAll('td');
    tdelement.forEach(function (element){
        element.setAttribute("style", "border-width: 2px")});
    let thelement = document.querySelectorAll('th');
    thelement.forEach(function (element){
    element.setAttribute("style", "border-width: 2px")});
</script>
</body>
</html>

templates/all_answers.html
{% extends "__base__.html" %}
{% block title %}
    Zarządzaj odpowiedziami
{% endblock %}
{% block content %}
    <ul id="possible">Dostępne odpowiedzi
        {% for item in answers %}
            <li>{{ item.all_kind_answers }}</li>
        {% endfor %}
    </ul>
    <br>
    <button type="button" class="btn btn-primary btn-sm" id="but">Dodaj</button>
    <script>
        let ul = document.querySelector('#possible')
        let but = document.querySelector('#but')
        let div = document.createElement('div')
        let form = document.createElement('form')
        let first_input = document.createElement('input')
        let second_input = document.createElement('input')
        first_input.name = "answer"
        first_input.placeholder = "Możliwa odpowiedź"
        first_input.type = "text"
        second_input.type = "submit"
        second_input.value = "Zapisz"
        form.setAttribute("action", "add_answer")
        form.appendChild(first_input)
        form.appendChild(second_input)
        div.appendChild(form)
        but.addEventListener("click", function () {
        ul.appendChild(div)
        })
    </script>
{% endblock %}

templates/create_test.html
{% extends "__base__.html" %}
{% block content %}
    <form method="post">
    {% csrf_token %}
{{ form.as_p }}
    <input type="submit" value="Zapisz">
    </form>
    <script>
    let datefield = document.querySelector('#id_date')
    datefield.type="date"
    let nowdate = new Date()
    nowdate = nowdate.toISOString().substr(0,10)
    datefield.setAttribute("min", nowdate)
    </script>
{% endblock %}

templates/index.html
{% extends '__base__.html' %}
{% block title %}
    Testy Pomorskiego ZPN
{% endblock %}
{% block content %}
<h2>Witaj na portalu do testowania wiedzy z przepisów gry w piłkę nożną</h2><BR>
    {% if user.is_authenticated %}
        <div class="container">
                <h5>Zalogowany jako {{ user.first_name }} {{ user.last_name }}</h5><BR>
        <a href="{% url 'logout' %}" class="nav_link"><i class='bx bx-log-out nav_icon'></i> <span class="nav_name">Wyloguj</span> </a>

        </div>

    {% else %}
    <div class="container">
    <h4>Szybkie logowanie</h4>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Zaloguj">
    </form>
    <br>
        Nie masz konta?
    <a href="{% url 'sign_up' %}">Załóż je</a>
    </div>
    {% endif %}
{% endblock %}

templates/login.html
{% extends '__base__.html' %}
{% block title %}
    Zaloguj
{% endblock %}
{% block content %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Zaloguj">
    </form>

{% endblock %}

templates/manage_group.html
{% extends '__base__.html' %}
{% block title %}
Zarządzaj użytkownikami
{% endblock %}
{% block content %}
<form method="POST">
Dodaj grupę:
{% csrf_token %}
{{ form }}
<input type="submit" value="Dodaj">
</form><BR>
    <table>
    <tr>
        <th>Grupa</th>
        <th>Uprawnienia</th>

    </tr>
        {% for item in grop %}
            <td>{{ item.name }}</td>
            <td id="last-column"><small><a href="/group/{{ item.id }}">Szczegóły</a> <a href="#" class="confirm-delete">Usuń</a> </small> </td>
            </tr>
    {% endfor %}
    </table>
{% endblock %}

templates/manage_users.html
{% extends '__base__.html' %}
{% block title %}
Zarządzaj użytkownikami
{% endblock %}
{% block content %}
    <table>
    <tr>
        <th>Użytkownik</th>
        <th>Aktywny</th>
        <th>Email</th>
        <th>Liga</th>
        <th>Zalogowany</th>
        <th>Dołączył</th>
        <th>Edytuj/usuń</th>
    </tr>
        {% for item in users %}
            <tr>
            <td>{{ item }}</td>
            <td>{{ item.is_active }}</td>
            <td>{{ item.username }}</td>
            <td>{{ item.league }}</td>
            <td>{{ item.last_login }}</td>
            <td>{{ item.date_joined }}</td>
            <td id="last-column"><small><a href="{% url "edit_user" item.slug %}">Edytuj</a> <a href="#" class="confirm-delete">Usuń</a> </small> </td>
            </tr>
    {% endfor %}
    </table>
   <script type="text/javascript">
   $(document).ready(function(){

     $('.cofirm-delete').click(function(){
        event.preventDefault()
         $(this).closest('td').remove()


     });
   });
   </script>
{% endblock %}

templates/reset_password.html
{% extends "__base__.html" %}
{% block title %}
    Resetuj hasło {{ user.first_name }} {{ user.last_name }}
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Zapisz">
    </form>
    <BR>
{% endblock %}

templates/signup.html
{% extends "__base__.html" %}
{% block title %}
    Rejestracja
{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <label for="league2">Klasa</label>
    <select name="league2">
        {% for item in league %}
            <option value="{{ item.slug }}">{{ item }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Zarejestruj">
</form>
{% endblock %}

templates/solve_test.html
{% extends "__base__.html" %}
{% block title %}
    Dostępne testy
{% endblock %}
{% block content %}
    <table>
    <tr>
        <th>Test</th>
        <th>Dnia</th>
        <th>Akcja</th>
    </tr>
    {% for item in tests %}
        <tr>
            <td>{{ item.test_number }}</td>
            <td>{{ item.date_time }}</td>
            <td><a href="{% url 'specific_test_solve' item.slug %}">Rozwiąż</a></td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

templates/test_details.html
{% extends '__base__.html' %}
{% block title %}
    Test {{ test.test_name }}
{% endblock %}
{% block content %}
    <table>
    <tr>
        <th>Test</th>
        <th>Data</th>
        <th>Dla klasy</th>
        <th>Stworzony</th>
        <th>Pytań</th>
        <th>Akcja</th>
    </tr>

            <tr>
            <td>{{ test.test_name }}</td>
            <td>{{ test.date }}</td>
            <td>{{ test.for_league }}</td>
            <td>{{ test.created_by.username }}</td>
            <td>{{ test.questions.count }}</td>
            <td><small><a href="{% url 'edit_test' test.slug%}">Edytuj</a>
                    <a href="#" class="dropdownclasstest">Usuń</a>
                    <div class="sub-menuintest">
                        <p>Czy na pewno usunąć?</p>
                        <a href="{% url 'delete_test' test.slug %}">Usuń</a>
                        <a href="{% url 'test_detail' test.slug%}">Zostaw</a>
                    </div></small></td>
            </tr>
    </table>
    <br>
    <table>
    <tr>
        <th>Numer</th>
        <th class="col-8">Pytanie</th>
        <th>Możliwe odpowiedzi</th>
        <th class="col-1">Odpowiedź komisji</th>
        <th>Akcja</th>
    </tr>
        {% for item in que %}
        <tr class="col-8">
            <td>{{ forloop.counter }}</td>
            <td>{{ item.question.add_question }}</td>
            <td>{% for possbile in possible_answers%}{% if possbile.question.id == item.question.id %}
                {{ possbile.question_possible_answers.all_kind_answers }}{% endif %}{% endfor %}</td>
            <td class="col-1" style="text-align: center">
                {% for answer in correct_answers%}{% if answer.question.id == item.question.id %}
                {{ answer.question_correct_answers.all_kind_answers }}{% endif %}{% endfor %}</td>
            <td><a href="{% url 'remove_question_from_test' item.question.slug item.id %}">Usuń</a> </td>
        </tr>
        {% endfor %}
    </table>
        <!--script to confirm delete -->
       <script type="text/javascript">
   $(document).ready(function(){
     //jquery for toggle sub menus
     $('.dropdownclasstest').click(function(){
       $(this).next('.sub-menuintest').slideToggle();
     });
   });
   </script>
{% endblock %}

templates/user_test_check.html.html
{% extends "__base__.html" %}
{% block title %}
    Test {{ user_solved }}
{% endblock %}
{% block content %}
        <table>
        <tr>
            <th>Osoba</th>
            <th>Wynik</th>
        </tr>
        <tr>
            <td>{{ user_solved }}</td>
            <td>{{ result.result }} / {{ solution.count }}</td>
        </tr>
    </table>
    <br>
    <table>
    <tr>
        <th class="col-1">Nr</th>
        <th>Pytanie</th>
        <th>Odpowiedź</th>
        <th>Prawidłowa odpowiedź</th>
        <th>Punkt</th>
    </tr>
        {% for item in solution %}
            <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ item.question.question.add_question }}</td>
            <td>{{ item.user_response}}</td>
            <td>{% for answer in correct %}{% if item.question.question.id == answer.question.id %}{{ answer.question_correct_answers.all_kind_answers }}, {% endif %}{% endfor %}</td>
            <td id="res">{{ item.result}}</td>
            </tr>
        {% endfor %}

    </table>

    <script>
    let tdfields = document.querySelectorAll('#res')
    tdfields.forEach(function (element) {
        if (element.innerText==1.0) {
            element.style.backgroundColor = "green"
            element.parentElement.style.backgroundColor = "#80FF45"

        }
        if (element.innerText==0) {
            element.parentElement.style.backgroundColor = "#FF8989"

        }
    })
    </script>
{% endblock %}

templates/user_test_history.html
{% extends "__base__.html" %}
{% block title %}
    Historia testów
{% endblock %}
{% block content %}
    <table>
    <tr>
        <th>Test</th>
        <th>Przeprowadzony dnia</th>
        <th>Wynik</th>
    </tr>
    {% for item in tests %}
        <tr>
        <td>{{ item.test_number.test_name }}</td>
        <td>{{ item.test_number.date }}</td>
        <td>{{ item.result }} <a href="{% url 'result_of_test' item.organise_test_slug.slug %}">Szczegóły</a> </td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

templates/user_tests.html
{% extends "__base__.html" %}
{% block title %}
    Historia testów
{% endblock %}
{% block content %}
    <table>
        <tr>
            <th>Użytkowik</th>
            <th>Test</th>
            <th>Wynik</th>
            <th>Szczegóły</th>
        </tr>
        {% for item in user_test  %}
            <tr>
            <td>{{ item.user }}</td>
            <td>{{ item.test_number.test_name }}</td>
            <td>{{ item.result }}</td>
            <td><a href="{% url 'specific_test_to_check' item.organise_test_slug.slug item.user.slug %}">Szczegóły</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}